### PR TITLE
DB2 with Docker

### PR DESCRIPTION
**Pull request by andrevtg**
### Description
Docs for running DB2 in a container instead of installing it.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@slnode ok to test

**Comment by ssh24** [comment]
@andrevtg Could you please sign the [`Contributor License Agreement`](https://cla.strongloop.com/agreements/strongloop/loopback-connector-db2) before we can proceed with checking in the PR?

**Comment by andrefernandes** [comment]
Signed the loooong agreement. Not sure if that compromised my immortal soul though.

**Comment by ssh24** [comment]
@andrefernandes, @andrevtg Needs to sign the agreement since it his PR. :)

**Comment by dhmlau** [comment]
I think @andrevtg needs to sign the CLA, because this id was used to create this PR.

**Comment by dhmlau** [comment]
Thanks @andrevtg for your contribution.  Your PR has been landed.

**Pull request merged**
