### PR TITLE
CI build cleanup

### PR DESCRIPTION
**Pull request by tonyffrench**

### CODE REVIEW

**Comment by rmg** [comment]
CI is now failing with a bunch of this:
```
Connection fails:  { [Error: [IBM][CLI Driver] SQL1337N  The service "undefined" was not found.
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] SQL1337N  The service "undefined" was not found.\r\n',
  state: '08001' } 
```

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
Getting closer, now failing with:
```
  1) db2 imported features manipulation create should refuse to create object with duplicate id:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\test\manipulation.test.js:308:24
      at createCallback (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\dao.js:337:20)
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\lib\db2.js:9:12337
      at cbForWork (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:150:34)
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-connector\lib\sql.js:417:7
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\lib\db2.js:9:4961

  2) db2 imported features manipulation updateOrCreate should preserve properties with dynamic setters on update:

      Uncaught AssertionError: expected 'bar' to be 'bar-BAR'
      + expected - actual

      -bar
      +bar-BAR
      
      at Assertion.fail (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\should\lib\assertion.js:91:17)
      at Assertion.Object.defineProperty.value (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\should\lib\assertion.js:163:19)
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\test\manipulation.test.js:648:35
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\dao.js:1630:5
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\dao.js:1561:9
      at done (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:167:19)
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:40:16
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\dao.js:1545:13
      at doNotify (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:93:49)
      at doNotify (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:93:49)
      at Function.ObserverMixin._notifyBaseObservers (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:116:5)
      at Function.ObserverMixin.notifyObserversOf (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:91:8)
      at Function.ObserverMixin._notifyBaseObservers (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:114:15)
      at Function.ObserverMixin.notifyObserversOf (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:91:8)
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\dao.js:1541:17
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:157:13
      at _each (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:57:9)
      at Object.async.each (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:156:9)
      at allCb (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\dao.js:1497:13)
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-connector\lib\sql.js:1075:7
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:166:22
      at doNotify (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:93:49)
      at DB2.ObserverMixin._notifyBaseObservers (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:116:5)
      at DB2.ObserverMixin.notifyObserversOf (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:91:8)
      at cbForWork (C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-datasource-juggler\lib\observer.js:156:14)
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\node_modules\loopback-connector\lib\sql.js:417:7
      at C:\jenkins\workspace\loopback-connector-db2\c502254b\lib\db2.js:9:4961

  3) db2 imported features relations hasMany can be declared in short form:
     Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0601N  The name of the object to be created is identical to the existing name "USER09183.Author" of type "TABLE".  SQLSTATE=42710

      at Error (native)
```

**Comment by qpresley** [comment]
2. above needs some new code written to implement updateOrCreate.  Working on it now.

**Comment by tonyffrench** [comment]
@robot test please

**Comment by rmg** [comment]
@tonyffrench fyi, `robot` isn't a StrongLoop account, so they may not appreciate the notification spam :-P

Use @slnode since we at least control that one ;-)

**Pull request merged**
