### PR TITLE
Remove extraneous properties

### PR DESCRIPTION
**Pull request by qpresley**
Remove properties that are no longer used in this connection from test/init.js

### CODE REVIEW

**Comment by qpresley** [comment]
Merging with admin as the failures above are due to new code in loopback-ibmdb which are a day or so ahead of required changes coming in node-ibm_db.  When the node-ibm_db changes are in the errors will be fixed.

**Comment by superkhau** [comment]
@qpresley We should backport to loopback-2.x too.

**Comment by qpresley** [comment]
@superkhau why, these are just cleanup changes.  The properties have no meaning that backporting seems like a make work project.

**Comment by superkhau** [comment]
@qpresley It'll keep other backports to this file easier in the future (prevent perpetual merge conflicts). Don't worry only takes a second -- I did it for you here: https://github.com/strongloop/loopback-connector-db2/pull/65

**Pull request merged**
