### PR TITLE
fix: lb4 discover giving error

### PR DESCRIPTION
**Pull request by pktippa**
Signed-off-by: Pradeep Kumar Tippa <pktippa@gmail.com>

## Checklist

- [x] DCO (Developer Certificate of Origin) [signed in all commits](https://loopback.io/doc/en/contrib/code-contrib.html)
- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [x] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by pktippa** [comment]
Add reviewer @achrinza

**Review by achrinza — APPROVED** [review]

**Review by agnes512 — APPROVED** [review]

**Comment by achrinza** [comment]
@pktippa Suggestion to reword the commit message to use `fix:` instead

**Comment by pktippa** [comment]
@achrinza changes done as suggested.

**Review by dhmlau — APPROVED** [review]

**Comment by pktippa** [comment]
@dhmlau @achrinza can you merge this PR or let me know if there are any other changes to be done.

**Comment by dhmlau** [comment]
@pktippa, sorry about the delay. Your PR has been landed! 🎉

**Comment by dhmlau** [comment]
I just published `loopback-connector-db2@2.2.3` that contains this fix. Thanks.

**Comment by pktippa** [comment]
Thanks

**Pull request merged**
