### PR TITLE
Exclude 'deps'  and '.github'  from npm publish

### PR DESCRIPTION
**Pull request by emonddr**
Related to: https://github.com/strongloop/loopback-connector-mssql/issues/222 

Using similar fix applied to loopback-connector-mssql : https://github.com/strongloop/loopback-connector-mssql/pull/226 

## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-connector-db2) 👈

- [x] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [ ] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by agnes512** [comment]
I couldn't reproduce the issue. Do you know how I can verify if the change fixes it on my end?

**Comment by emonddr** [comment]
> I couldn't reproduce the issue. Do you know how I can verify if the change fixes it on my end?

Hi @agnes512 , there is no need to reproduce the issue. In issue 222 the user was on a `windows` machine and trying to install loopback-connector-mssql . They ran into a permissions problem because the `node_modules` and `deps\juggler_v3\node_modules` were included in the latest version. So Miroslav and Raymond came up with a way to avoid this problem in PR 226.  I was told all connectors with  deps\juggler-v3 and deps\juggler-v4 directories should be given similar fix. So I will be creating a similar PR for all the involved connectors.

**Comment by agnes512** [comment]
@slnode test please

**Comment by emonddr** [comment]
Since we are using a "files" entry in the package.json, we no longer need .npmignore .

**Pull request merged**
