### PR TITLE
Update counts

### PR DESCRIPTION
**Pull request by qpresley**
### Description
Update db2.js to use the SQL COUNT function for Update/Delete functions

#### Related issues
- None

### Checklist

- [ x] New tests added or existing tests modified to cover all changes
- [ x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by b-admike** [comment]
Changes LGTM, but we need tests which verify the new behaviour.

**Comment by kjdelisle** [comment]
Reopening this, hopefully we can update this with test coverage soon and land it rather than close it.

**Comment by jannyHou** [comment]
Rebased and triggered a new build. I think all tests for `update` in juggler already cover the change here, we can check it in if CI is green.

**Comment by kjdelisle** [comment]
@slnode test please

**Pull request merged**
